### ISSUE TITLE
Feature request: 35 lb or 15 kg women's bar

### ISSUE THREAD

**Issue by ericacooksey** [nmunson/warmup-reps#16]
Any chance of adding a 35 lb or 15 kg women's bar as an option to the warm-up calculator? Thanks :)

**Comment by augieschwer** [comment]
Ping. There's a PR to address this, it just needs to be merged. @nmunson do you need help with this project?

**Comment by nmunson** [comment]
Done!  I merged and deployed the pull request from @jacobmovingfwd so it's live now.  Thanks for the patience.
