### ISSUE TITLE
Feature request: allow for higher max weights

### ISSUE THREAD

**Issue by mdw2020** [nmunson/warmup-reps#19]
It would be useful to be able to set max weights above 500 lbs.

**Comment by kast69** [comment]
Agreed.  Im going for 415,  calculator only goes up to 400.

**Comment by kast69** [comment]
Seems like a easy fix

**Comment by kast69** [comment]
All of the weighted ones.  I'm not an elite crossfiter but I'm a strong ish
guy.  Middle of the road to upper middle. I couldn't use the programs
becuase the weights were all too light.  I ended up finding a starting
strength spreadsheet online. Deadlifts, squats, were all too low.  It's
been a while since i looked at the problem so I don't remember what was on
there other than it looked cool enough to send you guys an email saying,
the weights are all too low.

Sincerely,
Anthony Sakakeeny
978-771-9731 c
978-296-0123 o
978-475-0069 f

**Comment by jacobmovingfwd** [comment]
I'd put 1000lbs as the max, just because there's no reason to have a cap
,so make it really big.

**Comment by nmunson** [comment]
It's set lower than 1000 though just for usability, if the majority of users are only using a quarter of the slider it doesn't make as much sense.  Would an increase of 200 across all exercises be reasonable?  It's an easy change.

**Comment by jacobmovingfwd** [comment]
If the slider can be distinct per-movement, I'd suggest:
Deadlift: 500
Squat: 400
Upper body: 300

**Comment by divsmith** [comment]
@nmunson, what would you think about a user-configurable max?

**Comment by kast69** [comment]
I uninstalled the app.   What exercise are you asking for?

Squat 600lbs
Deadlier 600lbs
PC 350lbs
Weighted pull ups 200lbs
Press 300
Bench 450
Row 300lbs

**Comment by mdw2020** [comment]
I can understand not having an arbitrarily high max (i.e. 1000) as it makes the slider meaningless for folks using lighter weights. At some point warm-up reps become 'just add another 45 lb plate on each side'. 

I think the current maxes are still well below where you are doing that, however; I'd suggest setting maxes, at least for the "Max Single" program to:
Deeds 700
Squats 600
Bench 500
Overhead Press 400

5x5 could perhaps be 100 lbs. less across the board.

....and, no, my maxes aren't anywhere near that, but it provides a plenty of room at the top without making the tool unusable for someone just starting out.

Thanks, overall really appreciate warmupreps.com and have turned a number of new lifters on to it.

**Comment by nmunson** [comment]
Thanks to the PR from @jacobmovingfwd this PR is now merged and deployed.  Sorry for the wait!

**Comment by mdw2020** [comment]
Really appreciate this modification- nice update overall for Dec 2019.

Thank you!
