### ISSUE TITLE
Progressive Web Apps act like instant mobile apps

### ISSUE THREAD

**Issue by Jakeisthesnake** [nmunson/warmup-reps#24]
Since this website has a mobile version, it can be saved on a phone and functions as a app that doesn't need WiFi. I saved it on my iPhone and it works just great with no internet. Just thought I would put it out there since I didn't see that mentioned on Reddit.

Also might be worth starting a Patreon... this apps definitely earns it.

**Comment by ethanx94** [comment]
@Jakeisthesnake Not to spam, but if you like the PWA approach please try my fork as well. I've been trying to get in contact with the original author but I did a full rewrite with a library called OnsenUI that will adapt to use either Material Design or Aqua to give it a real native experience.

[https://ethanx94.github.io/warmup-reps/](https://ethanx94.github.io/warmup-reps/)

**Comment by Jakeisthesnake** [comment]
Thank you!
